databases:  
  ems:
    driver: org.postgresql.Driver
    host: db-sbos-dev-instance-1.ctzvobutq8dd.ap-east-1.rds.amazonaws.com
    port: 5432
    database: mangopie
    username: mangopie
    password: m5HvWYoDqhMa5sV
  energy:
    driver: org.postgresql.Driver
    host: db-sbos-dev-instance-1.ctzvobutq8dd.ap-east-1.rds.amazonaws.com
    port: 5432
    database: energy
    username: energy
    password: tP85JwSBqLzJUWD1
  hierarchy:
    driver: org.postgresql.Driver
    host: db-sbos-dev-instance-1.ctzvobutq8dd.ap-east-1.rds.amazonaws.com
    port: 5432
    database: hierarchy
    username: hierarchy
    password: ArJMQkkhhHuXfjh
  organization:
    driver: org.postgresql.Driver
    host: db-sbos-dev-instance-1.ctzvobutq8dd.ap-east-1.rds.amazonaws.com
    port: 5432
    database: organization
    username: organization
    password: 2Yqi1xC64C2rLF8