databases:  
  ems:
    driver: org.postgresql.Driver
    host: db-sbos-prod-instance-1.c10qruchydgi.ap-southeast-1.rds.amazonaws.com
    port: 5432
    database: mangopie
    username: mangopie
    password: bBX8pkRi8sjbFgf
  energy:
    driver: org.postgresql.Driver
    host: db-sbos-prod-instance-1.c10qruchydgi.ap-southeast-1.rds.amazonaws.com
    port: 5432
    database: energy
    username: energy
    password: CstIgRq8XVi97Tw
  hierarchy:
    driver: org.postgresql.Driver
    host: db-sbos-prod-instance-1.c10qruchydgi.ap-southeast-1.rds.amazonaws.com
    port: 5432
    database: hierarchy
    username: hierarchy
    password: iCgdkiZMIEAyuFI
  organization:
    driver: org.postgresql.Driver
    host: db-sbos-prod-instance-1.c10qruchydgi.ap-southeast-1.rds.amazonaws.com
    port: 5432
    database: organization
    username: organization
    password: hYhPoD3sK6KHiGfVC9XF
  city:
    driver: org.postgresql.Driver
    host: db-sbos-prod-instance-1.c10qruchydgi.ap-southeast-1.rds.amazonaws.com
    port: 5432
    database: city
    username: city
    password: rXGajaRh4haudHiwBVFR
  node:
    driver: org.postgresql.Driver
    host: db-sbos-prod-instance-1.c10qruchydgi.ap-southeast-1.rds.amazonaws.com
    port: 5432
    database: node
    username: node
    password: UENusX4u28ULVdcA

#codes: "cdnis,isf,hkcec,tts,vtchk,topform"    
#codes: "swire,suss,starbucks" 
#codes: "smartone,sais-sg,mtr"
#codes: "HTHK,hgc,harrow-hk"
#codes: "FXHK,esf,en-trak"
#codes: "dragages,bochk,alibaba,AIAHK"

codes: "isf"



components_binding: False

grpc:
  energy:
    # host: "energy-grpc:50051"
    # kubectl port-forward pod/energy-grpc-5cd96d65cd-2zzkl 50055:50051
    host: "localhost:50055"
